apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastly-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastly-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastly-operator
    spec:
      serviceAccountName: fastly-operator
      securityContext:
        runAsUser: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
      - name: webhook-tls
        secret:
          secretName: fastly-operator-webhook-tls
      containers:
      - name: operator
        image: fastly-operator:latest
        imagePullPolicy: IfNotPresent
        args:
        - '-leader-election=true'
        - '-webhook-port=9443'
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: health
        - containerPort: 9443
          name: webhook-server
        volumeMounts:
        - name: webhook-tls
          mountPath: /var/run/webhook-serving-certs
          readOnly: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
          initialDelaySeconds: 3
          periodSeconds: 2
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
          initialDelaySeconds: 3
          periodSeconds: 2
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 