apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastly-operator
  labels:
    app: fastly-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastly-operator
  template:
    metadata:
      labels:
        app: fastly-operator
    spec:
      containers:
      - name: fastly-operator
        image: fastly-operator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m" 