apiVersion: platform.seatgeek.io/v1alpha1
kind: FastlyCertificateSync
metadata:
  name: example-1
spec:
  suspend: false
  certificateName: example-1
  tlsConfigurationIds:
  - "FvmqG3m7zgnbyw2PBTzxHw" # (HTTP/3 & TLS v1.3) - configuration IDs are account specific, usage in other accounts will need to change this
  - "aDDySyCAF3iZzH4ZXW2dEA" # (HTTP/3 & TLS v1.3 + 0RTT) - configuration IDs are account specific, usage in other accounts will need to change this
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-1
  annotations:
    platform.seatgeek.io/enable-fastly-sync: "true"
spec:
  commonName: example-1.com
  secretName: example-1-tls
  isCA: false
  duration: 1h
  renewBefore: 5m
  usages:
    - server auth
  issuerRef:
    kind: Issuer
    name: local-issuer
  privateKey:
    rotationPolicy: Always
  dnsNames:
  - "example-1.com"
  - "*.example-1.com"
